### ISSUE TITLE
Issue with some kernel versions

### ISSUE THREAD

**Issue by io-qar** [lwfinger/rtw88#272]
I noticed that after the kernel being updated, the driver doesn't work (it happens only sometime though). But after I reintall it with instructions in the readme file as following:

1. `sudo make clean`;
2. `sudo make uninstall`;
3. `sudo depmod`; (that's the only extra command)
4. `sudo make`;
5. `sudo make sign-install`.

After this sequence the driver works again. So I think the generating dependencies should also be included in the updating instruction in the readme, shouldn't it? Why does the driver work sometimes with this command be included during the installation?

**Comment by morrownr** [comment]
Hi @io-qar 

> I noticed that after the kernel being updated, the driver doesn't work...

That is actually by design. This repo is designed to be a development repo for drivers that are destined for the Linux Mainline kernel. Adding support for dkms would actually be a challenge given that this repo installs numerous drivers.

The below line is in the README. Should we move it to a different location?

```
Remember, every new kernel requires this step - no exceptions. If the kernel update means that you have no network, skip the 'git pull' and build the driver as it is, but run git pull once you have connectivity, and rebuild if any updates were pulled.
```
